#image: "registry.gitlab.com/dps8m/dps8m"
image: "registry.gitlab.com/unused0/docker_images"

stages:
  - build_linux
  - build_mingw

#  - list
#
#list job:
#  stage: list
#  only:
#    - master
#  script:
#    - find / -name libwinpthread-1.dll

build linux:
  stage: build_linux
  only:
    - master
  script:
    - make
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8
      - /builds/dps8m/dps8m/src/utils/prt2pdf

build mingw:
  stage: build_mingw
  only:
    - master
  script:
    - make CROSS=MINGW64
  artifacts:
    paths:
      - /builds/dps8m/dps8m/src/dps8/dps8.exe
      - /builds/libuv-mingw/.libs/libuv-1.dll
      - /usr/x86_64-w64-mingw32/sys-root/mingw/bin/libwinpthread-1.dll
      - /builds/dps8m/dps8m/src/utils/prt2pdf.exe

#test:
#  only:
#    - master
#  script:
#    - cd src/dps8; ./dps8 -v MR12.6e_install.ini
#    - cd src/dps8; cp root.dsk.reloaded root.dsk
#    - cd src/dps8; ./dps8 -v yoyodyne.ini
#    - cd src/dps8; cp root.dsk yoyodyne.root.dsk
#    - cd src/dps8; cp dska_01.dsk yoyodyne.dska_01.dsk

